name: Build Component in Native Environment

on:
  pull_request:
    branches: [ develop  ]
    paths: ['**/*.c', '**/*.cpp', '**/*.cc', '**/*.cxx', '**/*.h', '**/*.hpp', '**/*.sh' ]
    
jobs:
  build-systemtimemgr-on-pr:
    name: Build Remote-debugger component in github rdkcentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-device-mgt-service-test/native-platform:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .netrc file
        run: |
          echo "machine github.com login ${{ secrets.GITHUB_ACTOR }} password ${{ secrets.GITHUB_TOKEN }}" > ~/.netrc
          chmod 600 ~/.netrc

      - name: native build
        run: |
          chmod +x cov_build.sh
          sh -e cov_build.sh
