name: Build Component in Native Environment

on:
  push:
    branches: [ feature/RDK-52984_coverity ]
    paths: ['**/*.c', '**/*.cpp', '**/*.cc', '**/*.cxx', '**/*.h', '**/*.hpp']
    
jobs:
  build-systemtimemgr-on-pr:
    name: Build Remote-debugger component in github rdkcentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: native build
        run: |
          chmod +x cov_build.sh
          sh -e cov_build.sh
