name: Build Component in Native Environment

on:
  pull_request:
    branches: [ develop  ]
    paths: ['**/*.c', '**/*.cpp', '**/*.cc', '**/*.cxx', '**/*.h', '**/*.hpp', '**/*.sh' ]
    
jobs:
  build-systemtimemgr-on-pr:
    name: Build Remote-debugger component in github rdkcentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-device-mgt-service-test/native-platform:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: remote_debugger

      - name: Checkout code rfc code
        uses: actions/checkout@v4
        with:
          path: remote_debugger

      - name: Check out dependent repostiories
        uses: actions/checkout@v4
        with:
          repository: 'rdkcentral/rfc'
          path: rfc

      - name: Check out dependent repostiories
        uses: actions/checkout@v4
        with:
          repository: 'rdkcentral/iarmmgrs'
          path: iarmmgrs
          
      - name: Check out dependent repostiories
        uses: actions/checkout@v4
        with:
          repository: 'rdkcentral/iarmbus'
          path: iarmbus

      - name: Check out dependent repostiories
        uses: actions/checkout@v4
        with:
          repository: 'rdkcentral/tr69hostif'
          path: tr69hostif


      - name: native build
        run: |
          cd remote_debugger
          chmod +x cov_build.sh
          sh -e cov_build.sh
